<a href="https://colab.research.google.com/github/cristianomendieta/fraudes-bancarias-CIDAMO/blob/main/random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Modelo sem resampling de dados

In [16]:
#importa base train e base test
data_train = pd.read_csv('/content/drive/MyDrive/cidamo/dadosTrain.csv')
data_test = pd.read_csv('/content/drive/MyDrive/cidamo/dadosTest.csv')

In [17]:
#visualizar cabecalho treino
data_train.head()

Unnamed: 0  X        date  ... faixasjob  faixascity        distGeo
0           1  0  2019-01-01  ...         2           1   78773.820754
1           2  1  2019-01-01  ...         2           1   30216.618410
2           3  2  2019-01-01  ...         4           1  108102.911712
3           4  3  2019-01-01  ...         3           7   95685.115476
4           5  4  2019-01-01  ...         1           1   77702.395165

[5 rows x 30 columns]

In [18]:
#visualizar cabecalho teste
data_test.head()

Unnamed: 0  Unnamed: 0.1  X  ... faixasjob faixascity        distGeo
0           0             1  0  ...       3.0        3.0   24613.746071
1           1             2  1  ...       2.0        3.0  104834.043428
2           2             3  2  ...       2.0        2.0   59204.795631
3           3             4  3  ...       3.0        1.0   27615.117073
4           4             5  4  ...       3.0        2.0  104423.174625

[5 rows x 31 columns]

In [19]:
atributes = ['cc_num', 'amt', 'gender', 'sec', 'faixascategory', 'faixasjob', 'faixascity', 'distGeo']

In [20]:
#definicao variaveis
X_train = data_train[atributes]
y_train = data_train['is_fraud']
X_test = data_test[atributes]
y_test = data_test['is_fraud']

#construcao do modelo
model = RandomForestClassifier()

#treinando o modelo
model = model.fit(X_train, y_train)
model

#dados de teste para o modelo
y_predict = model.predict(X_test)

In [21]:
#comparando gabarito e previsoes da maquina
gabarito = pd.DataFrame({'Gabarito': y_test, 'Previsao': y_predict})
gabarito

Gabarito  Previsao
0              0         0
1              0         0
2              0         0
3              0         0
4              0         0
...          ...       ...
555579         0         0
555580         0         0
555581         0         0
555582         0         0
555583         0         0

[555584 rows x 2 columns]

In [22]:
#metricas
print('Classification metrics: \n', metrics.classification_report(y_test,y_predict))
print('Acuracia: \n', accuracy_score(y_test, y_predict))
print('\n Confusion Matrix :\n', confusion_matrix(y_test, y_predict))

Classification metrics: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.61      0.13      0.21      2010

    accuracy                           1.00    555584
   macro avg       0.80      0.57      0.61    555584
weighted avg       1.00      1.00      1.00    555584

Acuracia: 
 0.9965495766616749

 Confusion Matrix :
 [[553405    169]
 [  1748    262]]


# Modelo com Undersample

In [23]:
#importa base
data_undersample = pd.read_csv('/content/drive/MyDrive/cidamo/undersample_data.csv')

In [24]:
#atributos
atributes = ['cc_num', 'amt', 'gender', 'sec', 'faixascategory', 'faixasjob', 'faixascity', 'distGeo']

#definicao variaveis
X_train = data_undersample[atributes]
y_train = data_undersample['is_fraud']
X_test = data_test[atributes]
y_test = data_test['is_fraud']

#construcao do modelo
model = RandomForestClassifier()

#treinando o modelo
model = model.fit(X_train, y_train)
model

#dados de teste para o modelo
y_predict = model.predict(X_test)

In [25]:
#comparando gabarito e previsoes da maquina
gabarito = pd.DataFrame({'Gabarito': y_test, 'Previsao': y_predict})
gabarito

Gabarito  Previsao
0              0         0
1              0         0
2              0         0
3              0         0
4              0         0
...          ...       ...
555579         0         0
555580         0         1
555581         0         0
555582         0         1
555583         0         0

[555584 rows x 2 columns]

In [26]:
#metricas
print('Classification metrics: \n', metrics.classification_report(y_test,y_predict))
print('Acuracia: \n', accuracy_score(y_test, y_predict))
print('\n Confusion Matrix :\n', confusion_matrix(y_test, y_predict))

Classification metrics: 
               precision    recall  f1-score   support

           0       1.00      0.96      0.98    553574
           1       0.01      0.12      0.02      2010

    accuracy                           0.96    555584
   macro avg       0.50      0.54      0.50    555584
weighted avg       0.99      0.96      0.98    555584

Acuracia: 
 0.958755111738279

 Confusion Matrix :
 [[532420  21154]
 [  1761    249]]


# Modelo com Oversample

In [27]:
#importa base
data_oversample = pd.read_csv('/content/drive/MyDrive/cidamo/oversample_data.csv')

In [28]:
#atributos
atributes = ['cc_num', 'amt', 'gender', 'sec', 'faixascategory', 'faixasjob', 'faixascity', 'distGeo']

#definicao variaveis
X_train = data_oversample[atributes]
y_train = data_oversample['is_fraud']
X_test = data_test[atributes]
y_test = data_test['is_fraud']

#construcao do modelo
model = RandomForestClassifier()

#treinando o modelo
model = model.fit(X_train, y_train)
model

#dados de teste para o modelo
y_predict = model.predict(X_test)

In [29]:
#comparando gabarito e previsoes da maquina
gabarito = pd.DataFrame({'Gabarito': y_test, 'Previsao': y_predict})
gabarito

Gabarito  Previsao
0              0         0
1              0         0
2              0         0
3              0         0
4              0         0
...          ...       ...
555579         0         0
555580         0         0
555581         0         0
555582         0         0
555583         0         0

[555584 rows x 2 columns]

In [30]:
#metricas
print('Classification metrics: \n', metrics.classification_report(y_test,y_predict))
print('Acuracia: \n', accuracy_score(y_test, y_predict))
print('\n Confusion Matrix :\n', confusion_matrix(y_test, y_predict))

Classification metrics: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.36      0.08      0.13      2010

    accuracy                           1.00    555584
   macro avg       0.68      0.54      0.56    555584
weighted avg       0.99      1.00      0.99    555584

Acuracia: 
 0.9961733959221288

 Confusion Matrix :
 [[553302    272]
 [  1854    156]]


# Modelo com SMOTE

In [31]:
#importa base
data_smote = pd.read_csv('/content/drive/MyDrive/cidamo/smote_data.csv')

In [32]:
#atributos
atributes = ['cc_num', 'amt', 'gender', 'sec', 'faixascategory', 'faixasjob', 'faixascity', 'distGeo']

#definicao variaveis
X_train = data_smote[atributes]
y_train = data_smote['is_fraud']
X_test = data_test[atributes]
y_test = data_test['is_fraud']

#construcao do modelo
model = RandomForestClassifier()

#treinando o modelo
model = model.fit(X_train, y_train)
model

#dados de teste para o modelo
y_predict = model.predict(X_test)

In [33]:
#comparando gabarito e previsoes da maquina
gabarito = pd.DataFrame({'Gabarito': y_test, 'Previsao': y_predict})
gabarito

Gabarito  Previsao
0              0         0
1              0         0
2              0         0
3              0         0
4              0         0
...          ...       ...
555579         0         0
555580         0         0
555581         0         0
555582         0         0
555583         0         0

[555584 rows x 2 columns]

In [34]:
#metricas
print('Classification metrics: \n', metrics.classification_report(y_test,y_predict))
print('Acuracia: \n', accuracy_score(y_test, y_predict))
print('\n Confusion Matrix :\n', confusion_matrix(y_test, y_predict))

Classification metrics: 
               precision    recall  f1-score   support

           0       1.00      0.99      0.99    553574
           1       0.03      0.09      0.04      2010

    accuracy                           0.99    555584
   macro avg       0.51      0.54      0.52    555584
weighted avg       0.99      0.99      0.99    555584

Acuracia: 
 0.9852659543831356

 Confusion Matrix :
 [[547224   6350]
 [  1836    174]]
